"""
Fingerprint Laptop Unlock System

Authentication Proof Verifier

Responsible for verifying authentication
proof generated by Android device.

Version:
1.0
"""


import hmac
import hashlib
import logging


from security_layer.key_manager import (
    KeyManager
)



class ProofVerifier:
    """
    Verifies authentication proofs.
    """



    def __init__(
        self,
        key_manager: KeyManager
    ):

        self.key_manager = (
            key_manager
        )



    def generate_expected_proof(
        self,
        device_id: str,
        challenge: str,
        timestamp: str
    ) -> str:
        """
        Generate expected authentication proof.

        Used internally for verification.
        """


        key = (
            self.key_manager
            .get_device_key(
                device_id
            )
        )


        if not key:

            raise ValueError(
                "Device key not found"
            )



        message = (
            challenge
            +
            timestamp
        )


        proof = hmac.new(

            key,

            message.encode(
                "utf-8"
            ),

            hashlib.sha256

        ).hexdigest()



        return proof



    def verify(
        self,
        request
    ) -> bool:
        """
        Verify authentication proof.

        Args:
            request:
                AuthenticationRequest object

        Returns:
            True if proof valid
        """


        try:

            expected_proof = (
                self.generate_expected_proof(

                    request.device_id,

                    request.challenge,

                    request.timestamp

                )
            )


            received_proof = (
                request.authentication_proof
            )


            result = hmac.compare_digest(

                expected_proof,

                received_proof

            )



            if result:

                logging.info(
                    "Authentication proof verified"
                )

            else:

                logging.warning(
                    "Invalid authentication proof"
                )



            return result



        except Exception as error:

            logging.error(
                "Proof verification failed: %s",
                error
            )


            return False